apiVersion: v1
kind: Service
metadata:
  name: {{ include "btcd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "btcd.name" . }}
    helm.sh/chart: {{ include "btcd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
  selector:
    app.kubernetes.io/name: {{ include "btcd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
